# This workflow builds the percosisd binary for amd64 and arm64 on Darwin and Linux.
#
# This workflow runs:
# - on pushes to main
# - on every pull requests
# - when manually triggered
#
# Caching strategy
# This code will store the Go modules cache based on the hash of your go.sum file,
# ensuring that the cache will be invalidated when your dependencies change.
# The cache will be stored on a per-branch basis, which should prevent cache pollution issues between different branches.

name: Build percosisd

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "v[0-9]**"
  workflow_dispatch:

env:
  GO_VERSION: '1.20.5'

jobs:
  build:
    name: percosisd-${{ matrix.targetos }}-${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64

    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v3
      -
        name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.wasm
            **/**.go
            go.mod
            go.sum
            Makefile
            .github/workflows/build.yml
      -
        name: 🐿 Setup Golang
        uses: actions/setup-go@v4
        if: env.GIT_DIFF
        with:
          go-version: ${{env.GO_VERSION}}
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
      -
        name: Download Dependencies
        if: env.GIT_DIFF
        run: go mod download
      -
        name: Build percosisd
        if: env.GIT_DIFF
        run: |
          GOWRK=off go build cmd/percosisd/main.go
      -
        name: Upload percosisd artifact
        if: env.GIT_DIFF
        uses: actions/upload-artifact@v4
        with:
          name: percosisd-${{ matrix.targetos }}-${{ matrix.arch }}
          path: cmd/percosisd/percosisd
